import "./globals.css";
import Header from "@/components/Header";
import { Outfit } from "next/font/google";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "MediSync",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={outfit.className}
      >
        <div>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
